name: puro
description: A powerful tool for installing and upgrading Flutter versions
version: 1.4.11
repository: https://github.com/pingbird/puro
homepage: https://puro.dev

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  analyzer: ^7.4.5
  args: ^2.3.1
  async: ^2.9.0
  clock: ^1.1.1
  collection: ^1.18.0
  dart_console: ^4.1.1
  file: ^7.0.0
  freezed_annotation: ^3.0.0
  http: ^1.1.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  mutex: ^3.0.0
  neoansi: ^0.3.2+1
  path: ^1.8.2
  petitparser: ^6.0.1
  process: ^5.0.0
  protobuf: ^4.0.0
  pub_semver: ^2.1.1
  rxdart: ^0.28.0
  stack_trace: ^1.10.0
  typed_data: ^1.3.1
  vm_service: ^15.0.0
  xml: ^6.1.0
  yaml: ^3.1.1
  yaml_edit: ^2.0.3

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^3.0.6
  json_serializable: ^6.4.1
  lints: ^5.1.1
  test: ^1.16.0
